export const FETCH_TASKS_REQUEST = "FETCH_TASKS_REQUEST";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_FAILURE = "FETCH_TASKS_FAILURE";
export const FETCH_TASK_BY_ID = "FETCH_TASK_BY_ID";
export const DELETE_TASK_BY_ID_REQUEST = "DELETE_TASK_BY_ID_REQUEST";
export const DELETE_TASK_BY_ID_SUCCESS = "DELETE_TASK_BY_ID_SUCCESS";
export const DELETE_TASK_BY_ID_FAILURE = "DELETE_TASK_BY_ID_SUCCESS";
